#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WORK_LOAD 5
#define MIN_EDGES_PARALLEL 5
#define MAX_EDGES_PARALLEL 10

#define FILENAME_LENGTH 20
#define NUM_LENGTH 2
#define MEDIUM_FILENAME_LENGTH 10
#define EXTENSION_LENGTH 14

#endif