#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WORK_LOAD 50
#define MIN_EDGES_PARALLEL 18
#define MAX_EDGES_PARALLEL 20

#define NUM_VERTICES 10
#define MIN_EDGES_SERIAL 4
#define MAX_EDGES_SERIAL 7

#define FILENAME_LENGTH 50
#define NUM_LENGTH 2
#define MEDIUM_FILENAME_LENGTH 10
#define EXTENSION_LENGTH 14

#endif